import { describe, expect, it } from 'vitest'
import { LineSplitter } from '../server/ndjson.js'
import { applyEvent, applyEvents, createLiveState, type LiveEvent, type LiveState } from '@/lib/events'
import { F_COMPLETE, F_UNREADABLE, F_VISITED, Tree } from '@/lib/tree'
import { loadFixtures, mulberry32, type Fixture } from './fixtures'

const fixtures = loadFixtures()
const byName = (n: string) => {
  const f = fixtures.find((x) => x.name === n)
  if (!f) throw new Error(`fixture ${n} missing; run: python3 scripts/make_fixtures.py --force`)
  return f
}

const MASK = F_UNREADABLE | F_VISITED | F_COMPLETE

/** What the totals must be given only the dirs that were visited (those with an `s` event). */
function expectedFromVisited(t: Tree, ownB: ArrayLike<number>, ownF: ArrayLike<number>) {
  const totB = new Float64Array(t.n)
  const totF = new Float64Array(t.n)
  for (let i = t.n - 1; i >= 0; i--) {
    if (t.isVisited(i)) {
      totB[i] += ownB[i]
      totF[i] += ownF[i]
    }
    if (t.parent[i] >= 0) {
      totB[t.parent[i]] += totB[i]
      totF[t.parent[i]] += totF[i]
    }
  }
  return { totB, totF }
}

/** Brute-force subtree completeness: every dir in the subtree visited. */
function bruteComplete(t: Tree) {
  const c = new Uint8Array(t.n)
  for (let i = 0; i < t.n; i++) c[i] = t.isVisited(i) ? 1 : 0
  for (let i = t.n - 1; i > 0; i--) if (!c[i]) c[t.parent[i]] = 0
  return c
}

function run(events: LiveEvent[]): LiveState {
  const st = createLiveState()
  applyEvents(st, events)
  return st
}

function expectStructureEqual(live: Tree, snap: Tree) {
  expect(live.n).toBe(snap.n)
  for (let i = 0; i < snap.n; i++) {
    if (live.parent[i] !== snap.parent[i] || live.names[i] !== snap.names[i]) {
      throw new Error(`dir ${i}: live (${live.parent[i]}, ${live.names[i]}) != snapshot (${snap.parent[i]}, ${snap.names[i]})`)
    }
    if ((live.flags[i] & MASK) !== (snap.flags[i] & MASK)) {
      throw new Error(`dir ${i} ${snap.names[i]}: live flags ${live.flags[i]} != snapshot flags ${snap.flags[i]}`)
    }
  }
}

describe('fixtures', () => {
  it('were generated by the real scanner', () => {
    const names = fixtures.map((f) => f.name).sort()
    expect(names).toEqual(['big', 'empty', 'flat', 'small', 'small-du', ...(names.includes('unreadable') ? ['unreadable'] : [])].sort())
    for (const f of fixtures) {
      expect(f.events[0][0]).toBe('h')
      expect(f.events[f.events.length - 1][0]).toBe('e')
    }
  })

  it('include a genuinely partial (SIGTERM) scan', () => {
    const big = byName('big')
    expect(big.snapshot.meta.complete).toBe(false)
    const t = big.snapshot.tree
    let unvisited = 0
    for (let i = 0; i < t.n; i++) if (!t.isVisited(i)) unvisited++
    expect(unvisited).toBeGreaterThan(0)
    expect(t.isComplete(0)).toBe(false)
  })
})

describe('event reducer == snapshot', () => {
  for (const f of fixtures) {
    const partial = !f.snapshot.meta.complete
    it(`${f.name}${partial ? ' (interrupted)' : ''}: same tree, totals and complete flags`, () => {
      const st = run(f.events)
      const live = st.tree
      const snap = f.snapshot.tree
      expectStructureEqual(live, snap)

      if (!partial) {
        for (let i = 0; i < snap.n; i++) {
          if (
            live.ownBytes[i] !== snap.ownBytes[i] || live.ownFiles[i] !== snap.ownFiles[i] ||
            live.totalBytes[i] !== snap.totalBytes[i] || live.totalFiles[i] !== snap.totalFiles[i]
          ) {
            throw new Error(`dir ${i} ${snap.names[i]}: totals differ from snapshot`)
          }
        }
        expect(live.isComplete(0)).toBe(true)
        expect(st.end?.totals).toEqual(f.snapshot.meta.totals)
      } else {
        // dirscan.py writes the partial own_* of the dir it was in the middle of when SIGTERM
        // landed, but never emits an `s` event for it. So the stream can only account for
        // visited dirs: that is exactly what the reducer must produce, and the snapshot may
        // differ only on dirs it did not mark visited.
        const { totB, totF } = expectedFromVisited(snap, snap.ownBytes, snap.ownFiles)
        let inFlight = 0
        for (let i = 0; i < snap.n; i++) {
          if (live.totalBytes[i] !== totB[i] || live.totalFiles[i] !== totF[i]) {
            throw new Error(`dir ${i} ${snap.names[i]}: live total ${live.totalBytes[i]} != expected ${totB[i]}`)
          }
          if (live.ownBytes[i] !== snap.ownBytes[i] || live.ownFiles[i] !== snap.ownFiles[i]) {
            expect(snap.isVisited(i)).toBe(false) // only the unvisited, in-flight dir may differ
            inFlight++
          }
        }
        expect(inFlight).toBeLessThanOrEqual(1) // one dir can be mid-scandir at SIGTERM
        expect(live.isComplete(0)).toBe(false)
        expect(st.end?.complete).toBe(false)
      }

      expect(st.largest).toEqual(f.snapshot.largest)
      expect(st.extensions).toEqual(f.snapshot.extensions)
      expect(st.end?.complete).toBe(f.snapshot.meta.complete)
    })
  }
})

describe('incremental bookkeeping', () => {
  // After (nearly) every event the incrementally maintained totals and completeness must
  // match a from-scratch recompute over the tree as it stands at that moment.
  for (const name of ['small', 'unreadable', 'big']) {
    if (!fixtures.some((f) => f.name === name)) continue
    it(`${name}: matches brute force at intermediate points`, () => {
      const f = byName(name)
      const st = createLiveState()
      const step = Math.max(1, Math.floor(f.events.length / 400))
      f.events.forEach((ev, k) => {
        applyEvent(st, ev)
        if (k % step && k !== f.events.length - 1) return
        const t = st.tree
        const { totB, totF } = expectedFromVisited(t, t.ownBytes, t.ownFiles)
        const comp = bruteComplete(t)
        for (let i = 0; i < t.n; i++) {
          if (t.totalBytes[i] !== totB[i] || t.totalFiles[i] !== totF[i]) {
            throw new Error(`after event ${k}: dir ${i} totals ${t.totalBytes[i]} != ${totB[i]}`)
          }
          if (t.isComplete(i) !== (comp[i] === 1)) {
            throw new Error(`after event ${k}: dir ${i} complete=${t.isComplete(i)} but brute force says ${comp[i]}`)
          }
        }
      })
    })
  }

  it('a dir becomes complete exactly when its last descendant is scanned', () => {
    const st = createLiveState()
    applyEvents(st, [
      ['h', { version: 2, root: '/r', host: 'h', mode: 'apparent', pid: 1, started_epoch: 0, cache_file: null }],
      ['n', 0, -1, 'r'],
      ['n', 1, 0, 'a'],
      ['n', 2, 1, 'b'],
      ['s', 0, 10, 1, 2],
      ['s', 1, 20, 2, 2],
    ])
    const t = st.tree
    expect([t.isComplete(0), t.isComplete(1), t.isComplete(2)]).toEqual([false, false, false])
    expect(t.totalBytes[0]).toBe(30)
    applyEvent(st, ['s', 2, 5, 1, 2])
    expect([t.isComplete(0), t.isComplete(1), t.isComplete(2)]).toEqual([true, true, true])
    expect([t.totalBytes[0], t.totalFiles[0]]).toEqual([35, 4])
    // a new dir discovered under a complete one un-completes the chain
    applyEvent(st, ['n', 3, 2, 'c'])
    expect([t.isComplete(0), t.isComplete(1), t.isComplete(2), t.isComplete(3)]).toEqual([false, false, false, false])
  })

  it('an unreadable dir counts as scanned, and is flagged', () => {
    const f = byName('unreadable')
    const st = run(f.events)
    const t = st.tree
    const locked = [...Array(t.n).keys()].filter((i) => t.isUnreadable(i))
    expect(locked.length).toBeGreaterThan(0)
    for (const i of locked) expect(t.isVisited(i) && t.isComplete(i)).toBe(true)
    expect(st.tree.isComplete(0)).toBe(true)
  })

  it('a repeated `s` for the same dir adjusts totals instead of double counting', () => {
    const st = run([
      ['h', { version: 2, root: '/r', host: 'h', mode: 'apparent', pid: 1, started_epoch: 0, cache_file: null }],
      ['n', 0, -1, 'r'],
      ['n', 1, 0, 'a'],
      ['s', 1, 10, 1, 2],
      ['s', 1, 15, 2, 2],
      ['s', 0, 1, 1, 2],
    ])
    expect([st.tree.totalBytes[0], st.tree.totalFiles[0]]).toEqual([16, 3])
    expect(st.tree.pending[0]).toBe(0)
  })

  it('ignores unknown event types', () => {
    const st = createLiveState()
    applyEvent(st, ['zzz', 1, 2, 3])
    expect(st.events).toBe(0)
  })

  it('rejects out-of-order dir ids', () => {
    const st = createLiveState()
    applyEvent(st, ['n', 0, -1, 'r'])
    expect(() => applyEvent(st, ['n', 5, 0, 'x'])).toThrow(/out of order/)
  })
})

describe('restart handling', () => {
  it('an `h` event resets all state, so a restarted scan replaces the old one', () => {
    const small = byName('small')
    const flat = byName('flat')
    const st = createLiveState()
    applyEvents(st, small.events.slice(0, Math.floor(small.events.length / 2)))
    expect(st.tree.n).toBeGreaterThan(1)
    applyEvents(st, flat.events)
    expect(st.resets).toBe(2)
    expectStructureEqual(st.tree, flat.snapshot.tree)
    expect(st.header?.root).toBe(flat.snapshot.meta.root)
    expect(st.extensions).toEqual(flat.snapshot.extensions)
  })
})

describe('partial lines (random byte chunks through the line splitter)', () => {
  function feed(f: Fixture, nextSize: () => number) {
    const sp = new LineSplitter()
    const st = createLiveState()
    const buf = f.eventBytes
    let at = 0
    while (at < buf.length) {
      const size = Math.max(1, nextSize())
      const lines: string[] = sp.push(buf.subarray(at, at + size))
      at += size
      for (const l of lines) applyEvent(st, JSON.parse(l) as LiveEvent)
    }
    expect(sp.pending).toBe(0) // file ends with a newline
    return st
  }

  for (const f of fixtures) {
    it(`${f.name}: any chunking yields the same state as one read`, () => {
      const whole = run(f.events)
      const seeds = f.eventBytes.length < 20_000 ? 12 : 4
      for (let seed = 1; seed <= seeds; seed++) {
        const rnd = mulberry32(seed)
        // mix of tiny, medium and large reads
        const st = feed(f, () => [1, 2, 7, 64, 500, 4096][Math.floor(rnd() * 6)] + Math.floor(rnd() * 5))
        expectStructureEqual(st.tree, whole.tree)
        expect(st.tree.totalBytes.subarray(0, whole.tree.n)).toEqual(whole.tree.totalBytes.subarray(0, whole.tree.n))
        expect(st.largest).toEqual(whole.largest)
        expect(st.end).toEqual(whole.end)
      }
    })
  }

  it('one byte at a time works too', () => {
    const f = byName('small')
    const st = feed(f, () => 1)
    expectStructureEqual(st.tree, f.snapshot.tree)
  })

  it('holds back a line until its newline arrives', () => {
    const sp = new LineSplitter()
    expect(sp.push(Buffer.from('["n",1,0,"a'))).toEqual([])
    expect(sp.pending).toBe(11)
    expect(sp.push(Buffer.from('"]'))).toEqual([])
    expect(sp.push(Buffer.from('\n["s"'))).toEqual(['["n",1,0,"a"]'])
    expect(sp.push(Buffer.from(',1]\n\n'))).toEqual(['["s",1]'])
  })

  it('does not split multi-byte characters that straddle a read boundary', () => {
    const line = Buffer.from('["n",1,0,"día-日本"]\n', 'utf8')
    for (let cut = 1; cut < line.length; cut++) {
      const sp = new LineSplitter()
      const out = [...sp.push(line.subarray(0, cut)), ...sp.push(line.subarray(cut))]
      expect(out).toEqual(['["n",1,0,"día-日本"]'])
    }
  })
})
